[package]
name = "test_hc"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "test_hc"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
serde_json = "1"

test_hc_integrity = { workspace = true } 
